# =========================
# Namespace
# =========================
apiVersion: v1
kind: Namespace
metadata:
  name: infra
---
# =========================
# Redis Secret
# =========================
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: infra
type: Opaque
stringData:
  redis-password: StrongRedisPassword123
---
# =========================
# MinIO Secret（统一使用）
# =========================
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: infra
type: Opaque
stringData:
  accesskey: MinioAccessKeyHere
  secretkey: MinioSecretKeyHere
---
# =========================
# Redis ConfigMap（不再写明文密码）
# =========================
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: infra
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    protected-mode no

    dir /data
    dbfilename dump.rdb

    appendonly yes
    appendfilename appendonly.aof
    appendfsync everysec

    maxmemory 1gb
    maxmemory-policy allkeys-lru

    save 900 1
    save 300 10
    save 60 10000
---
# =========================
# Redis StatefulSet
# =========================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: infra
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          command:
            - sh
            - -c
            - |
              redis-server /etc/redis/redis.conf \
                --requirepass "$REDIS_PASSWORD"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config
              mountPath: /etc/redis
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi
---
# =========================
# Redis Service
# =========================
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: infra
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
# =========================
# Redis Backup CronJob → MinIO
# =========================
apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-backup
  namespace: infra
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: minio/mc
              env:
                - name: MINIO_ENDPOINT
                  value: http://minio:9000
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-secret
                      key: accesskey
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-secret
                      key: secretkey
              command:
                - /bin/sh
                - -c
                - |
                  mc alias set minio $MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
                  mc mb -p minio/backups/redis || true
                  mc cp /data/dump.rdb minio/backups/redis/dump-$(date +%F-%H%M).rdb
              volumeMounts:
                - name: redis-data
                  mountPath: /data
          volumes:
            - name: redis-data
              persistentVolumeClaim:
                claimName: redis-data-redis-0
